language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- ./create_config.sh
script:
- npm test
- node lib/run.js
env:
  global:
  - secure: YzWHuqXSgtM1JyxrP4zhldX8QbN3+U7733AM8Lb6g1zEvh7GbMyzukqPP331ZURF3y5df4gFoGUe5flDJxWF92+qL+Ggar1pWvD7XHrWuEjh3r+VI/EeSQwAN2wbKOM1FIA4fQY56PWJJmz6ZcFcBF6Sw7WsJzBw63bo3WkrsP8=
  - secure: b7TIulLp7R63BCJqPhROW8ui9DEza//7c/ZknjQ2V1/Z8aPT8XOlREdUqsKJxQz8znxuYeIFcOH0Bh9uLq0ZH7Ah8//EtSmUzIcVzqe6Y0HvbUu/IFD0mZuWO+nWN+YJjmi75Z3oVFZLhZEPJs5LySpvCi5arEzeyvy4TNZSmv8=
  - secure: bsZT26Z3Szw6h4GTOzr07BVbOmuvtt5Io6K1Dfy7gPOPKlLF2hFtk39qs+sU2HyBZNAbyaB7sIggdvKG4GE5T4Z+KA35Xqg3f3vzSMcunwaLQ45XR6BTrFGEEYuy/ZEt4g9SVa++rHttcxXtHQ8qzVCMdX5bTRFdlIUq4nxZqak=
